criado o gressing game
mfcastellani/curso-ruby pull request #28
Opened 2021-07-22 01:01 UTC by francocaldas

2021-07-22 13:48 UTC, mfcastellani commented on aula-02/guessing-game/guessinggame.rb
> +    puts"Operação inválida"
Adicionar espaço após o `puts`

2021-07-22 13:51 UTC, mfcastellani requested changes
O código deve estar numa pasta `aula-02/guessing-game/franco/`, não diretamente na raiz.

2021-07-22 13:52 UTC, mfcastellani commented on aula-02/guessing-game/guessinggame.rb
> +      elsif (num - num2).abs < 10
por que usar o `abs` aqui e nos abaixo?

2021-07-22 13:53 UTC, francocaldas commented
Ok, vou providenciar as alterações

Em qui, 22 de jul de 2021 10:51, Marcelo Castellani <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> O código deve estar numa pasta aula-02/guessing-game/franco/, não
> diretamente na raiz.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mfcastellani/curso-ruby/pull/28#pullrequestreview-712790970>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADAKAFXZWNLEYIXA6IB5ILTZAO5XANCNFSM5AZASOAQ>
> .
>

2021-07-22 13:59 UTC, francocaldas commented on aula-02/guessing-game/guessinggame.rb
> +      elsif (num - num2).abs < 10
Só pra evitar que o resultado da subtração seja um número negativo

2021-07-26 00:41 UTC, mfcastellani approved these changes

2021-07-26 00:42 UTC, merged