bruno-bastos.rb
mfcastellani/curso-ruby pull request #34
Opened 2021-07-24 04:58 UTC by vits56

2021-07-26 00:44 UTC, mfcastellani requested changes

2021-07-26 00:44 UTC, mfcastellani commented on aula-02/guessing-game/bruno-bastos/guessing-game.rb
> +    puts "\nVocê acertou PARABÉNS!"
Puts não precisa do \n

2021-07-26 01:55 UTC, vits56 commented on aula-02/guessing-game/bruno-bastos/guessing-game.rb
> +    puts "\nVocê acertou PARABÉNS!"
alterei

2021-07-30 12:00 UTC, mfcastellani approved these changes

2021-07-30 12:00 UTC, merged