Adicionando pasta e subindo guessing game
mfcastellani/curso-ruby pull request #37
Opened 2021-07-25 20:58 UTC by mirandadiscos

2021-07-25 20:59 UTC, mirandadiscos reviewed
Subindo versão 1

2021-07-26 00:45 UTC, mfcastellani requested changes

2021-07-26 00:45 UTC, mfcastellani commented on aula-02/guessing-game/victor-guedes/file.rb
> +    end
Ajustar a identação

2021-07-30 12:01 UTC, mfcastellani approved these changes

2021-07-30 12:01 UTC, merged